version: '3.8'

services:
  # Node.js 后端服务
  server:
    image: ilpvcx/vcard-server:1.0  # 使用已构建的后端镜像
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # 数据库地址，使用容器名 db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=v-card
    networks:
      - app_network
    depends_on:
      - db  # 确保数据库先启动

  # MySQL 服务
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: v-card
    volumes:
      - ./db/v-card.sql:/docker-entrypoint-initdb.d/v-card.sql  # 初始化数据库
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  # Nginx 前端服务
  frontend:
    image: ilpvcx/vcard:1.0  # 使用已构建的前端镜像
    container_name: vite
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - server  # 确保后端服务先启动

networks:
  app_network:
    driver: bridge
